### ISSUE TITLE
Github uploading not working?

### ISSUE THREAD

**Issue by sumon117** [DroidDumps/phoenix_firmware_dumper#6]

**Comment by rokibhasansagar** [comment]
### Please state clearly

What is not working and where?
What were you doing?

Write clearly.

**Comment by sumon117** [comment]
![Screenshot_20211001-215357_Telegram](https://user-images.githubusercontent.com/56505303/135650788-894804cb-f68a-4976-808f-eede56a95a82.png)
![Screenshot_20211001-215412_Chrome](https://user-images.githubusercontent.com/56505303/135650834-5a949764-e171-42e8-a131-984603ace1ac.png)
It gave a link but dump not found in the link, its just created a empty repo in my github account nothing else

**Comment by rokibhasansagar** [comment]
You are running the dumper in a userbot environment.

Did you ran the `setup.sh` before running the `dumper.sh` command?
Have you exported the required values correctly?

And why is your GitHub Username (In the picture) has a "space" in the character?!

**Comment by sumon117** [comment]
Yes i did run the setup.sh  [here log](https://gist.github.com/SumonSN/eea7669b91aab6d2b6723918ae8d903b)
And why space in the link I don't know that, it was  generated by dumper sh [log](https://gist.github.com/SumonSN/b65dffa459397afec5eaec52ce01ba9d)

**Comment by sumon117** [comment]
Unfortunately i sent another dumper.sh file log, here the real one [log](https://gist.github.com/SumonSN/5cddcf339ec83e46f34f32860177661b)

**Comment by rokibhasansagar** [comment]
Please review this part:
https://github.com/DroidDumps/phoenix_firmware_dumper#how-to-use-it-to-upload-the-dump-in-github

Your GitHub User/ORG Name is not put correctly while processing the command. That's why script is trying to upload at "simon%20sn" User Account, which is Impossible to be there. Space can't be there.

Also, check whether the GitHub Token you provided is correctly put or not.

**Comment by sumon117** [comment]
I am understanding your point but i did add the .github_token file thats why it got my name for add in link and it was created a empty repo in github account as i said. But i did the .github_orgname as it optional

**Comment by sumon117** [comment]
*not

**Comment by sumon117** [comment]
I am closing this issue.maybe this just happened for me

**Comment by rokibhasansagar** [comment]
> I am understanding your point but i did add the .github_token file thats why it got my name for add in link and it was created a empty repo in github account as i said. But i did the .github_orgname as it optional

 .github_token and .github_orgname files Must be present and Must have a value in the text file. They are not optional.
Neither of them can have "space" in them.

But if only Token is given, Username will be taken from `git config`.

Set `git config --global user.name SumonSn`
Then try again.

Username is not a name which can have space and other special characters, it's the Unique ID that GitHub gives.

**Comment by sumon117** [comment]
I know what is username, thanks for your time btw
