### ISSUE TITLE
[Bug] Dumper Can't Extract Erofs & Squashfs images

### ISSUE THREAD

**Issue by techyminati** [DroidDumps/phoenix_firmware_dumper#7]
Hi, @rokibhasansagar , I tried to use this dumper on Erofs Image ( Oneplus 9 Pro , ColorOS12). The dumper cant extract erofs images yet, hence realmeUI 3.0/ColorOS12/OxygenOS12 Dumps are empty ( extracted partitions are empty). Please try to look in this. I'll drop Oneplus 9 Pro Firmware Down Below.

https://cloud.minati.workers.dev/LE2115_11_C_OTA_1090_all_f1ed2c_10100001.zip

Thanks!

**Comment by rokibhasansagar** [comment]
I had to look through the Original Dumper, and they also hadn't implemented this yet.
Luckily someone did a PR in https://github.com/AndroidDumps/dumpyara/pull/22 to fix this.
I'll try to adapt the code here.

**Comment by techyminati** [comment]
Thank You ! , Should I close this or keep it open until its fixed?

**Comment by rokibhasansagar** [comment]
> Thank You ! , Should I close this or keep it open until its fixed?

Let it be open for the time being.

**Comment by techyminati** [comment]
> > Thank You ! , Should I close this or keep it open until its fixed?
> 
> Let it be open for the time being.

okay, sure.

**Comment by techyminati** [comment]
@rokibhasansagar Dumper cant dump squashfs images too, please look into it too. Thanks

**Comment by rokibhasansagar** [comment]
@techyminati 
I think you should try https://github.com/DumprX/DumprX
It is a Continuation Project of this with lots of new Patches.
Or maybe use https://github.com/DumprX/DumprX-CI-Bot for Remote Dumping.

I'm not able to work on this repository for a lo..ong time.
You might say, this is **_Abandoned by Me_** 😢
