### ISSUE TITLE
Freezing?

### ISSUE THREAD

**Issue by ThirstyMick** [DroidDumps/phoenix_firmware_dumper#8]
Already up to date.
Already up to date.
Already up to date.
Extracting firmware on: /data/data/com.termux/files/home/phoenix_firmware_dumper/out
./dumper.sh: line 249: 7z: command not found
./dumper.sh: line 276: 7z: command not found
LG KDZ Detected.
[+] Extracting all partitions from v2 file!

[+] Extracting K50010l_00_NA2_US_OP_1121.dz to ./K50010l_00_NA2_US_OP_1121.dz

I get to this point and it just stops. I have tried numerous diff .kdz files. Each one same spot. Any ideas? FYI if a Noob could have anyone to look down on it would be me! Lol .. I literally have no idea what's going on! And I'm absorbing info way to fast and I think I might be near a stroke! 🤗 But if u say it slow enough I catch on quickly. Please any help?

**Comment by rokibhasansagar** [comment]
### Sorry for late explanation 😓 

The script hides many operation's dictations (what is happening when, etc.), so it's hard to understand for everybody.

Initial Problem: `7z: command not found` 
Solution: Install `p7zip-full` (or `p7zip` package in termux before running). May be some other programs are missing. Investigate `setup.sh` file as this script  were meant to run in either Alpine Linux or Ubuntu/Debian.

💡 Tips: Head to https://github.com/DumprX/DumprX for more Stable changes in Support. It might work in termux too.
